name: faraday
description: g_faraday command-line application.
version: 1.3.0
homepage: https://github.com/gfaraday/cli

executables:
  faraday:

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  logging: ^1.0.2
  ansicolor: ^2.0.1
  args: ^2.3.0
  g_json: ^4.0.0
  shell: ^2.0.0
  dio: ^4.0.4
  recase: ^4.0.0
  analyzer: ^3.1.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
