name: faraday
description: g_faraday command-line application.
version: 2.0.7
homepage: https://github.com/gfaraday/cli

executables:
  faraday:

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  path: ^1.8.1
  logging: ^1.0.2
  ansicolor: ^2.0.1
  args: ^2.3.0
  g_json: ^4.0.0
  # shell: ^2.0.0
  # dio: ^4.0.4
  recase: ^4.0.0
  analyzer: ^3.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
