name: faraday
description: g_faraday command-line application.
version: 3.0.0
homepage: https://github.com/gfaraday/cli

executables:
  faraday:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3
  logging: ^1.2.0
  ansicolor: ^2.0.1
  args: ^2.4.2
  g_json: ^4.1.0
  # shell: ^2.0.0
  # dio: ^4.0.4
  recase: ^4.1.0
  analyzer: ^6.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
