name: faraday
description: g_faraday command-line application.
version: 1.1.7
homepage: https://github.com/gfaraday/cli

executables:
  faraday:

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  logging: ^0.11.4
  ansicolor: ^1.0.4
  args: ^1.6.0
  g_json: ^3.0.0
  shell: ^1.0.1
  dio: ^3.0.10
  recase: ^3.0.0
  analyzer: ^0.40.3
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
